# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: clients.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rclients.proto\x12\x07\x63lients\"\x1e\n\rClientRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\"2\n\x0e\x43lientResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2P\n\rClientService\x12?\n\x0c\x44\x65leteClient\x12\x16.clients.ClientRequest\x1a\x17.clients.ClientResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'clients_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CLIENTREQUEST']._serialized_start=26
  _globals['_CLIENTREQUEST']._serialized_end=56
  _globals['_CLIENTRESPONSE']._serialized_start=58
  _globals['_CLIENTRESPONSE']._serialized_end=108
  _globals['_CLIENTSERVICE']._serialized_start=110
  _globals['_CLIENTSERVICE']._serialized_end=190
# @@protoc_insertion_point(module_scope)
